// <auto-generated />
using System;
using ApontamentoInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApontamentoApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApontamentoDomain.Entity.ApontamentoUsuario", b =>
                {
                    b.Property<int>("CodUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ApFim");

                    b.Property<DateTime>("ApInicio");

                    b.Property<DateTime>("ApIntervalo");

                    b.Property<DateTime>("ApRetorno");

                    b.Property<string>("CodEmpresa");

                    b.HasKey("CodUsuario");

                    b.ToTable("ApontamentosUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
